/**
 * Property-based / fuzz tests for VersionManager.
 *
 * Invariants that must hold for any sequence of next/confirm/rollback:
 * 1. current is always ≥ 0
 * 2. next() always returns current + 1 before the call
 * 3. confirmed versions are never in pendingVersions
 * 4. pendingVersions contains only versions generated by next()
 * 5. hasPending ↔ pendingCount > 0
 * 6. after rollback(v), v is not in pendingVersions
 */
import { describe, it, expect } from 'vitest';
import { VersionManager } from '../../../src/channel/VersionManager.js';

function makePrng(seed: number) {
  let s = seed;
  return () => {
    s = (s * 1664525 + 1013904223) & 0xffffffff;
    return (s >>> 0) / 0x100000000;
  };
}

describe('VersionManager — property tests', () => {
  describe('Property: current is always ≥ initialVersion', () => {
    it('current never goes below 0 after any operations (1000 sequences)', () => {
      const rng = makePrng(1);
      for (let trial = 0; trial < 1000; trial++) {
        const vm = new VersionManager();
        const inFlight: number[] = [];

        const ops = 10 + Math.floor(rng() * 20);
        for (let i = 0; i < ops; i++) {
          const r = rng();
          if (r < 0.4) {
            inFlight.push(vm.next());
          } else if (r < 0.7 && inFlight.length > 0) {
            const idx = Math.floor(rng() * inFlight.length);
            const v = inFlight.splice(idx, 1)[0]!;
            vm.confirm(v);
          } else if (inFlight.length > 0) {
            const idx = Math.floor(rng() * inFlight.length);
            const v = inFlight.splice(idx, 1)[0]!;
            vm.rollback(v);
          }
          expect(vm.current).toBeGreaterThanOrEqual(0);
        }
      }
    });
  });

  describe('Property: hasPending ↔ pendingCount > 0', () => {
    it('hasPending is always consistent with pendingCount (500 sequences)', () => {
      const rng = makePrng(2);
      for (let trial = 0; trial < 500; trial++) {
        const vm = new VersionManager();
        const inFlight: number[] = [];

        for (let i = 0; i < 15; i++) {
          const r = rng();
          if (r < 0.5) {
            inFlight.push(vm.next());
          } else if (inFlight.length > 0) {
            const idx = Math.floor(rng() * inFlight.length);
            const v = inFlight.splice(idx, 1)[0]!;
            if (rng() < 0.5) vm.confirm(v); else vm.rollback(v);
          }
          expect(vm.hasPending).toBe(vm.pendingCount > 0);
        }
      }
    });
  });

  describe('Property: confirmed versions never appear in pendingVersions', () => {
    it('confirmed versions are absent from pendingVersions (500 trials)', () => {
      const rng = makePrng(3);
      for (let trial = 0; trial < 500; trial++) {
        const vm = new VersionManager();
        const confirmed = new Set<number>();
        const inFlight: number[] = [];

        for (let i = 0; i < 20; i++) {
          const r = rng();
          if (r < 0.4) {
            inFlight.push(vm.next());
          } else if (inFlight.length > 0) {
            const idx = Math.floor(rng() * inFlight.length);
            const v = inFlight.splice(idx, 1)[0]!;
            vm.confirm(v);
            confirmed.add(v);
          }
          const pending = new Set(vm.pendingVersions);
          for (const c of confirmed) {
            expect(pending.has(c)).toBe(false);
          }
        }
      }
    });
  });

  describe('Property: rolled-back versions are absent from pendingVersions', () => {
    it('after rollback(v), v is not in pendingVersions', () => {
      const rng = makePrng(4);
      for (let trial = 0; trial < 500; trial++) {
        const vm = new VersionManager();
        const inFlight: number[] = [];

        for (let i = 0; i < 15; i++) {
          const r = rng();
          if (r < 0.5) {
            inFlight.push(vm.next());
          } else if (inFlight.length > 0) {
            const idx = Math.floor(rng() * inFlight.length);
            const v = inFlight.splice(idx, 1)[0]!;
            vm.rollback(v);
            expect(vm.pendingVersions).not.toContain(v);
          }
        }
      }
    });
  });

  describe('Property: pendingCount matches actual in-flight count', () => {
    it('pendingCount equals manually tracked in-flight count (300 trials)', () => {
      const rng = makePrng(5);
      for (let trial = 0; trial < 300; trial++) {
        const vm = new VersionManager();
        const inFlight = new Set<number>();

        for (let i = 0; i < 20; i++) {
          const r = rng();
          if (r < 0.4) {
            const v = vm.next();
            inFlight.add(v);
          } else if (inFlight.size > 0) {
            const v = [...inFlight][Math.floor(rng() * inFlight.size)]!;
            inFlight.delete(v);
            if (rng() < 0.5) vm.confirm(v); else vm.rollback(v);
          }
          expect(vm.pendingCount).toBe(inFlight.size);
        }
      }
    });
  });

  describe('Property: next() always increments current by exactly 1', () => {
    it('next() = prev_current + 1 for 500 calls', () => {
      const vm = new VersionManager();
      for (let i = 0; i < 500; i++) {
        const before = vm.current;
        const v = vm.next();
        expect(v).toBe(before + 1);
        expect(vm.current).toBe(before + 1);
        vm.confirm(v); // keep current clean
      }
    });
  });

  describe('Property: pendingVersions are always a subset of generated versions', () => {
    it('no version appears in pendingVersions that was not produced by next()', () => {
      const rng = makePrng(6);
      const vm = new VersionManager();
      const generated = new Set<number>();

      for (let i = 0; i < 200; i++) {
        const r = rng();
        if (r < 0.5) {
          const v = vm.next();
          generated.add(v);
        } else {
          const pending = vm.pendingVersions;
          for (const p of pending) {
            expect(generated.has(p)).toBe(true);
          }
        }
      }
    });
  });

  describe('Property: confirm + rollback are both no-ops for non-in-flight versions', () => {
    it('calling confirm/rollback on non-in-flight does not change current (200 checks)', () => {
      const rng = makePrng(7);
      for (let trial = 0; trial < 200; trial++) {
        const vm = new VersionManager();
        vm.next(); vm.confirm(1); // version 1 is now confirmed

        const before = vm.current;
        // Call confirm/rollback on version 1 (already confirmed, not in-flight)
        vm.confirm(1);
        vm.rollback(1);
        expect(vm.current).toBe(before);

        // Call on a version that was never generated
        vm.confirm(9999);
        vm.rollback(9999);
        expect(vm.current).toBe(before);
      }
    });
  });

  describe('Property: initialVersion is respected', () => {
    it('next() from any initialVersion returns initialVersion + 1', () => {
      for (const init of [0, 1, 5, 100, 1000]) {
        const vm = new VersionManager(init);
        expect(vm.current).toBe(init);
        expect(vm.next()).toBe(init + 1);
      }
    });
  });
});
